### ISSUE TITLE
Problems with cp_mgmt_api_python_sdk - can't log in

### ISSUE THREAD

**Issue by dpround** [CheckPointSW/cp_mgmt_api_python_sdk#22]
[root@networks-test examples_python2]# python ./find_dup_ip.py
Enter server IP address or hostname:weed
Enter username: API_admin
Enter password:
Login failed:
APIResponse received a response which is not a valid JSON.

api_calls.json
[
    {
        "request": {
            "headers": {
                "Accept": "*/*",
                "Content-Length": 98,
                "Content-Type": "application/json",
                "User-Agent": "python-api-wrapper"
            },
            "payload": {
                "continue-last-session": false,
                "password": "****",
                "read-only": false,
                "user": "API_admin"
            },
            "url": "/web_api/login"
        },
        "response": {
            "data": null,
            "status_code": 403
        }
    }
]

This worked for me 12 months ago. I have updated the management version to R80.30 possibly since it last worked.

**Comment by chkp-yaelg** [comment]
Hi @dpround , please do the following:

- Reproduce the issue
- Connect to Mgmt via SSH and execute api status -s
- Send the output (.tgz file) to [yaelg@checkpoint.com](url)

**Comment by chkp-yaelg** [comment]
By default, the API server is configured to accept calls from local host only.
Therefore, trying to communicate with the API server from external clients, including running tests and viewing the documentation, will fail.

You can set the API to either accept calls from Management server only, all IP addresses that can be used for GUI clients or all IP addresses using the api-settings from Smart Console or from API command.
