### ISSUE TITLE
setup.py

### ISSUE THREAD

**Issue by Ariwahyu11** [CheckPointSW/cp_mgmt_api_python_sdk#28]
import setuptools
from setuptools import setup

setup(
    name="cpapi",
    version="1.1.2",
    author="API team",
    author_email="api_team@checkpoint.com",
    description="Check Point Management API SDK",
    long_description="Check Point API Python Development Kit simplifies the usage of the Check Point Management APIs. "
                     "The kit contains the API library project, "
                     "and sample projects demonstrating the capabilities of the library. "
                     "The kit is python 2 and 3 compatible code.",
    long_description_content_type="text",
    url="https://github.com/CheckPointSW/cp_mgmt_api_python_sdk.git",
    packages=setuptools.find_packages(),
    classifiers=[
        "Programming Language :: Python :: 2.7",
        "Programming Language :: Python :: 3",
        "License :: OSI Approved :: Apache License",
        "Operating System :: OS Independent",
    ],

)

help me

**Comment by chkp-yaelg** [comment]
Hi @Ariwahyu11 
What are you trying to do? and what did you run?
Do you get an error? which?

**Comment by chkp-yaelg** [comment]
Hi @Ariwahyu11 
It has been over 13 days since we last heard from you, so I wanted to let you know that I am closing this issue due to a lack of response. 
Feel free to open new issue if needed.
