### ISSUE TITLE
api endpoints called with limit are failing 

### ISSUE THREAD

**Issue by henriknoerr** [CheckPointSW/cp_mgmt_api_python_sdk#48]
Hey,

Not sure if this SDK is in use by anyone - If so this error is beyond me how it can exist for so long :) Or I am severly misunderstanding something? I hope so.

when calling any api call with the gen_api_query function from mgmt_api.py there is a hardcoded limit key value being injected.

from mgmt_api.py:
`payload.update({"limit": limit, "offset": iterations * limit + offset, "details-level": details_level})
`
this part makes any query that does not take a limit flag fail - like show-access-layer.

The fix is replacing it with something like:

   if limit > 0:
            payload.update({"limit": limit, "offset": iterations * limit, "details-level": details_level})
        else:
            payload.update({"details-level": details_level})

**Comment by chkp-edenbr** [comment]
Hi,
Show-access-layer isn't considered a query and should be called with api_call.
The plural form, show-access-layer**s**, is a query and should be called with api_query.

**Comment by chkp-edenbr** [comment]
We differentiate between simple commands and queries that may return more than one object.
You may create your own function in your repo that's specific to your requirements.
