### ISSUE TITLE
The rule to add in specific section parameter not accepting

### ISSUE THREAD

**Issue by Nakuldiwane** [CheckPointSW/cp_mgmt_api_python_sdk#51]
If we want to add a rule in a specific section (e.g we have a clean up rule, Main rule ) add a rule in "Main Rule" section at the bottom is not allowing

**Comment by chkp-edenbr** [comment]
Hi @Nakuldiwane ,

Please share the function, command and payload you are using.
Did you get an error when attempting to run the command? If so please share it as well.

Thanks,
Eden

**Comment by Nakuldiwane** [comment]
![image](https://user-images.githubusercontent.com/63498372/209778037-48eefa38-41d1-4ebf-af60-ad36ec36a145.png)

While using the parameter "position.bottom": "Main rule"

This gives a syntax error
![image](https://user-images.githubusercontent.com/63498372/209778270-457bdaad-345d-41b0-8017-36f94435f454.png)

![image](https://user-images.githubusercontent.com/63498372/209778242-3075c725-f0f5-4d7e-8599-0696f23f73a7.png)

**Comment by Nakuldiwane** [comment]
![image](https://user-images.githubusercontent.com/63498372/209785567-fb0a79ab-8653-4616-85c1-03810b21f7bf.png)

Thanks for that point.

Now facing this issue.

**Comment by chkp-edenbr** [comment]
Hi @Nakuldiwane ,

Our API documentation contains usage examples https://sc1.checkpoint.com/documents/latest/APIs/index.html#web/add-access-rule~v1.9%20 
The position should be written as follows: 
"position" : {
    "bottom" : "main rule"
  }

**Comment by Nakuldiwane** [comment]
@chkp-edenbr : Thanks it is working
