### ISSUE TITLE
Python Version

### ISSUE THREAD

**Issue by vbaalagi** [CheckPointSW/cp_mgmt_api_python_sdk#52]
When I tried with my lab [EVE-NG R81.10] it appears that given script is executing, but it appears to run the script it requires Python3;
I assume, in my lab there is no policy i configured and  I could not test it, also under access rule base export getting null value, but seems its complied. So this development kit should working on Python3 version and higher, kindly change compatible version. 

[Expert@checkpoint-mgmt:0]# /opt/CPsuite-R81.10/fw1/Python/bin/python3 import_export_package.py 
Welcome to the Policy Package Import/Export Tool.
What would you like to do?
1. Import a package
2. Export a package
99. Exit
99

[Expert@checkpoint-mgmt:0]# /opt/CPsuite-R81.10/fw1/Python/bin/python2 import_export_package.py   
Traceback (most recent call last):
 File "import_export_package.py", line 27, in <module>
  raise Exception("Min Python version required is 3.7")
Exception: Min Python version required is 3.7
[Expert@checkpoint-mgmt:0]# 

[Expert@checkpoint-mgmt:0]# /opt/CPsuite-R81.10/fw1/Python/bin/python3.7 export_access_rulebase.py 
[Expert@checkpoint-mgmt:0]#

**Comment by chkp-edenbr** [comment]
Hi @vbaalagi ,

Python3 is available in R80.40 since JHF take 150 (PRJ-22353).
