### ISSUE TITLE
KeyError: 'sid'

### ISSUE THREAD

**Issue by Manchuker1120** [CheckPointSW/cp_mgmt_api_python_sdk#55]
File "/usr/local/lib/python3.9/site-packages/cpapi/mgmt_api.py", line 176, in _common_login_logic
    self.sid = login_res.data["sid"]
KeyError: 'sid'

**Comment by chkp-edenbr** [comment]
Hi @Manchuker1120 ,

We'll need more info to understand what caused the error:
1. Which version of the tool are you using?
2. What's the version of the MGMT machine you're using?
3. Does this error occur every time?
4. How did you use the login command?

Thanks,
Eden

**Comment by Manchuker1120** [comment]
I found the problem.
In my python code , I use "context = 'gaia_api'. I should use "context = 'web_api' 
Then , I should enable API in smartconsole client .
Thank U

**Comment by chkp-edenbr** [comment]
Great! Best regards,
Eden
