### ISSUE TITLE
Is there a good way for me to obtain all access sections under the layer?

### ISSUE THREAD

**Issue by Manchuker1120** [CheckPointSW/cp_mgmt_api_python_sdk#58]
Is there a good way for me to obtain all access sections under the layer?

**Comment by chkp-edenbr** [comment]
Hi @Manchuker1120 ,
You can try running the API show layer-structure:
https://sc1.checkpoint.com/documents/latest/APIs/index.html#cli/show-layer-structure~v1.9%20
Please note that for general questions we have our CheckMates community: https://community.checkpoint.com/
as these GitHub issues should regard our Python SDK.
