### ISSUE TITLE
pip install-python3

### ISSUE THREAD

**Issue by kaushik853** [CheckPointSW/cp_mgmt_api_python_sdk#7]
Hi team
i was trying to do pip install but getting this error (windows machine)
C:\>pip install cp_mgmt_api_python_sdk
Collecting cp_mgmt_api_python_sdk
  Could not find a version that satisfies the requirement cp_mgmt_api_python_sdk
 (from versions: )
No matching distribution found for cp_mgmt_api_python_sdk

Is it because of python3 in my windows machine?

**Comment by chkp-amiads** [comment]
Hi @kaushik853 , 
We are not yet supporting pip install. Soon enough we will support installing it from our github account:
pip install git+https://github.com/CheckPointSW/cp_mgmt_api_python_sdk.git
